parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
    impliedStrict: true
env: { node: true }
globals: { CONFIG: true, ENV: true, TEST: true, es6: true, Promise: true }
extends: "eslint:recommended"
rules:
  indent:
    - error
    - 2
  semi: error
  no-const-assign: error
  no-var: error
  prefer-const: error
  prefer-destructuring: ["warn", {"object": true, "array": false}]
  no-redeclare: error
  no-undef: warn
  camelcase: warn
  no-magic-numbers: warn
  global-require: error
  curly: error
  brace-style: 
    - error
    - stroustrup
  object-curly-newline: ["warn", { "multiline": true }]
  object-curly-spacing:
    - error
    - always
  no-template-curly-in-string: error
  func-style:
    - error
    - expression
  new-parens: error
  space-in-parens:
    - warn
    - never
  arrow-parens:
    - error
    - always
  space-before-function-paren: warn
  arrow-body-style: ["error", "as-needed", { "requireReturnForObjectLiteral": true }]
  no-useless-constructor: error
  new-cap: error
  no-multi-spaces: error
  no-mixed-spaces-and-tabs: error
  no-trailing-spaces: error
  quotes:
    - error
    - single
  eqeqeq:
    - error
    - smart
  dot-location:
    - error
    - property
  no-multiple-empty-lines: ["error", { "max": 2}]
  operator-linebreak: 
    - error 
    - after
  spaced-comment: 
    - warn 
    - always
  generator-star-spacing: ["error", {"before": false, "after": true}]
  prefer-promise-reject-errors: warn
  handle-callback-err: error
  no-console: off